name: password_manager
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_secure_storage: ^9.2.4
  crypto: ^3.0.6
  pointycastle: ^3.1.1
  password_hash_plus: ^4.0.0
  random_string: ^2.3.1
  encrypt: ^5.0.1
  sss256: ^1.0.0
  slip39: ^0.3.0
  ntcdcrypto: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

 